server:
 port: 8090

spring:
 application:
   name: wolf-cloud-provider-users
 zipkin:
    base-url: http://localhost:9411 #所有的数据提交到此服务之中
    sender:
      type: web       #提交的类型是web 服务
 sleuth:
    sampler:
      probability: 1.0 # 定义抽样比率，默认为0.1

logging:
  level:
    com.hyr.mapper: debug

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      #defaultZone: http://admin:enjoy@eureka1:7001/eureka,http://admin:enjoy@eureka2:7002/eureka,http://admin:enjoy@eureka3:7003/eureka
      defaultZone: http://admin:enjoy@127.0.0.1:7001/eureka
  instance:
    instance-id: wolf-cloud-provider-users
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 90  # 如果现在超过了5秒的间隔（默认是90秒）



info:
  app.name: wolf-cloud-provider-users
  company.name: enjoy
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always # 访问/actuator/health时显示详细信息,而不是仅仅显示up      