server:
  port: 80
 
spring:
  application:
    name: WOLF-CLOUD-CONSUMER
  zipkin:
    base-url: http://localhost:9411 #所有的数据提交到此服务之中
    sender:
      type: web       #提交的类型是web 服务
  sleuth:
    sampler:
      probability: 1.0 # 定义抽样比率，默认为0.1 
  boot:
    admin:
      client:
        # 配置admin-server地址
        url: http://localhost:9301  
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:enjoy@eureka1:7001/eureka,http://admin:enjoy@eureka2:7002/eureka,http://admin:enjoy@eureka3:7003/eureka