server:
  port: 8201

spring:
  application:
    name: WOLF-CLOUD-EMPLOYEE
#  zipkin:
#    base-url: http://localhost:9411
  # #设置Sleuth的抽样收集概率
#  sleuth:
#    sampler:
#      probability: 0.1
  zipkin:
    base-url: http://localhost:9411 #所有的数据提交到此服务之中
    sender:
      type: web       #提交的类型是web 服务
  sleuth:
    sampler:
      probability: 1.0 # 定义抽样比率，默认为0.1
  boot:
    admin:
      client:
        # 配置admin-server地址
        url: http://localhost:9301
eureka:
  client:
    #register-with-eureka: true
    #fetch-registry: true
    service-url:
      defaultZone: http://admin:enjoy@localhost:7001/eureka/