server:
  port: 7101

spring:
  application:
    name: wolf-cloud-config
  cloud:
    config:
      server:
        git: #配置存储的git仓库
          uri: https://github.com/enjoyeud/wolfconfig.git
          #username: xxxx
          #passwork: xxxx
          clone-on-start: true #开启启动时直接从git获取配置